// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHfAMVrZs_a5ced8uHBjmEiY4T2yu6ed0',
    appId: '1:921498085929:web:9cdd6eb9750987ece8ca38',
    messagingSenderId: '921498085929',
    projectId: 'movie-1944c',
    authDomain: 'movie-1944c.firebaseapp.com',
    storageBucket: 'movie-1944c.appspot.com',
    measurementId: 'G-YHWVWNCR2G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBW5GlGDs6C4rhbGfrDMePs7IpYBf4V_dU',
    appId: '1:921498085929:android:09bd4d58d4d1ab41e8ca38',
    messagingSenderId: '921498085929',
    projectId: 'movie-1944c',
    storageBucket: 'movie-1944c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtEtcXdgiBfhksgB6zYJbliD0xwfTD_lI',
    appId: '1:921498085929:ios:f633e94d72461c55e8ca38',
    messagingSenderId: '921498085929',
    projectId: 'movie-1944c',
    storageBucket: 'movie-1944c.appspot.com',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtEtcXdgiBfhksgB6zYJbliD0xwfTD_lI',
    appId: '1:921498085929:ios:a70a7841b6a992f7e8ca38',
    messagingSenderId: '921498085929',
    projectId: 'movie-1944c',
    storageBucket: 'movie-1944c.appspot.com',
    iosBundleId: 'com.example.movieApp.RunnerTests',
  );
}
