// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpNToxC-nXo17SPCOqja9ZYtMxKR0mXRo',
    appId: '1:1056064690152:web:72b8d8423a8cdb8d18f65d',
    messagingSenderId: '1056064690152',
    projectId: 'movieapp-65f77',
    authDomain: 'movieapp-65f77.firebaseapp.com',
    storageBucket: 'movieapp-65f77.appspot.com',
    measurementId: 'G-XGWH7T5M4L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtVfEgXaLpoQ9RbakVPWvvVwQd7VUx-wA',
    appId: '1:1056064690152:android:61c4a518dcab0f3118f65d',
    messagingSenderId: '1056064690152',
    projectId: 'movieapp-65f77',
    storageBucket: 'movieapp-65f77.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEiaedwfIesyk2pNqV1IIRnOqdJzVEV3M',
    appId: '1:1056064690152:ios:b6de8ca2744482df18f65d',
    messagingSenderId: '1056064690152',
    projectId: 'movieapp-65f77',
    storageBucket: 'movieapp-65f77.appspot.com',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEiaedwfIesyk2pNqV1IIRnOqdJzVEV3M',
    appId: '1:1056064690152:ios:72b78d5581ed3c6018f65d',
    messagingSenderId: '1056064690152',
    projectId: 'movieapp-65f77',
    storageBucket: 'movieapp-65f77.appspot.com',
    iosBundleId: 'com.example.movieApp.RunnerTests',
  );
}
